"""first database schema with User, Post, Animal, Habitat, Location, and AnimalToHabitat tables

Revision ID: 28cd8e978e36
Revises: 51ea14398c32
Create Date: 2018-10-13 22:52:07.000191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cd8e978e36'
down_revision = '51ea14398c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'year')
    # ### end Alembic commands ###
