"""first database schema with Artist, Event, Venue, and ArtistToEvent tables

Revision ID: 31a7f33cb3eb
Revises: 
Create Date: 2018-10-02 20:29:16.572862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a7f33cb3eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=120), nullable=True),
    sa.Column('extinction', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_bio'), 'animal', ['bio'], unique=True)
    op.create_index(op.f('ix_animal_extinction'), 'animal', ['extinction'], unique=True)
    op.create_index(op.f('ix_animal_name'), 'animal', ['name'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('continent', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_continent'), 'location', ['continent'], unique=True)
    op.create_table('habitat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('climate', sa.String(length=64), nullable=True),
    sa.Column('food', sa.String(length=64), nullable=True),
    sa.Column('locationID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locationID'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitat_climate'), 'habitat', ['climate'], unique=True)
    op.create_index(op.f('ix_habitat_food'), 'habitat', ['food'], unique=True)
    op.create_index(op.f('ix_habitat_name'), 'habitat', ['name'], unique=True)
    op.create_table('animal_to_habitat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animalID', sa.Integer(), nullable=True),
    sa.Column('habitatID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animalID'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['habitatID'], ['habitat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_to_habitat')
    op.drop_index(op.f('ix_habitat_name'), table_name='habitat')
    op.drop_index(op.f('ix_habitat_food'), table_name='habitat')
    op.drop_index(op.f('ix_habitat_climate'), table_name='habitat')
    op.drop_table('habitat')
    op.drop_index(op.f('ix_location_continent'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_animal_name'), table_name='animal')
    op.drop_index(op.f('ix_animal_extinction'), table_name='animal')
    op.drop_index(op.f('ix_animal_bio'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
